cfpb/curriculum-review-tool

- satellite/admin.py
- satellite/models.py
- satellite/tests.py
- satellite/views.py
This PR adds a skeleton Django satellite app named `satellite`.
> Add Django satellite app

- setup.py
It's just not a distributable package without one
> initial setup file

- .travis.yml
There are improvements that could be made here, but I think this gets us up and going.
-
-
-
-
- @user
-
-
> initial travis.yml

- .travis.yml
This configures travis to build wheels, and attach them to any new release.
-
-
-
-
- @user
-
-
> Have Travis build wheels

- teachers_digital_platform/css/layout/survey-top.less
- teachers_digital_platform/css/organisms/dimension-selection-bar.less
- teachers_digital_platform/css/tdp.less
- teachers_digital_platform/css/utilities/center.less
- teachers_digital_platform/jinja2/teachers_digital_platform/prototypes/crt-survey.html
Update markup and styles for the dimension selection bar on the survey prototype page for Curriculum Review tool to match the design.
- Styles for for new atoms, molecules, organisms, and utilities.
- Updated markup for the main content are of the survey page.
- @rrstoll 
- The survey prototype page is at http://0.0.0.0:8000/tdp/prototypes/crt-survey/
- Add SVG icons.
> Theme crt dimension selection bar

- MANIFEST.in
- setup.py
This seems to test fine for me in my virtualenv, but I think it was working fine there before, too, so I'm not sure I've proven that it will work on Build. Worth a try though, I suppose?
> Add package_data to get this installing correctly with pip

- setup.py
- setup.sh
Add front-end setup script
- Add setup.sh
- Add reference to setup.sh in setup.py
- @user
> Add front-end setup script

- teachers_digital_platform/css/cf-enhancements/organisms/modals.less
Fix modals to allow z-index to work.
- Add `position: relative` to modals to allow z-index to work.
- @rrstoll 
> Fix placement of modals

- teachers_digital_platform/css/organisms/survey.less
Fix Curriculum Review tool survey layout in IE.
> Fix Curriculum Review tool survey layout in IE

- teachers_digital_platform/jinja2/teachers_digital_platform/crt-start.html
Updated content on the getting started page for the Curriculum review tool.
- Updated content on the getting started page
- @rrstoll 
> Update content on the getting started page

- teachers_digital_platform/crtool/src/__tests__/__snapshots__/QualityCriterionPage.test.js.snap
- teachers_digital_platform/crtool/src/js/components/pages/QualityCriterionPage.js
Final copy is in place
Added text input fields for four survey questions
> Update content for quality dimension page

- teachers_digital_platform/crtool/src/__tests__/__snapshots__/ContentElementaryCriterionPage.test.js.snap
- teachers_digital_platform/crtool/src/js/components/pages/content/ContentElementaryCriterionPage.js
- teachers_digital_platform/crtool/src/js/components/pages/content/ContentHighCriterionPage.js
- teachers_digital_platform/crtool/src/js/components/pages/content/ContentMiddleCriterionPage.js
Fix IDs on content dimensions so that they match the question numbers.
- Update IDs on content dimension questions.
- @rrstoll 
> Fix IDs on content dimensions

- teachers_digital_platform/crtool/src/js/components/pages/QualitySummaryPage.js
Add content to quality summary page.
- Content for quality summary page
- @rrstoll 
> Add content to quality summary page

- teachers_digital_platform/css/atoms/icon.less
Fix large icon size.
- Large icon size is now 110% instead of 120%
- @rrstoll 
> Fix large icon size

- teachers_digital_platform/css/tdp.less
- teachers_digital_platform/css/temp/button-links.less
Fix button link colors.
- Temporary fix for button link colors until cfpb/cfgov-refresh#3887 is merged.
- @rrstoll 
> Fix button link colors

- teachers_digital_platform/css/cf-enhancements.less
- teachers_digital_platform/css/cf-enhancements/atoms/select.less
- teachers_digital_platform/css/cf-enhancements/molecules/form-fields.less
- teachers_digital_platform/jinja2/teachers_digital_platform/crt-start.html
Re-order form elements on getting started page and fix height of select dropdowns.
- Re-order form element
- Height of select dropdowns
- @rrstoll 
> Fix getting started form

- teachers_digital_platform/crtool/src/__tests__/__snapshots__/EfficacyCriterionPage.test.js.snap
- teachers_digital_platform/crtool/src/js/components/pages/EfficacyCriterionPage.js
- teachers_digital_platform/crtool/src/js/components/pages/content/ContentElementaryCriterionPage.js
- teachers_digital_platform/jinja2/teachers_digital_platform/prototypes/crt-summary.html
Remove consecutive lead paragraphs.
- Consecutive lead paragraphs
- @rrstoll 
> Remove consecutive lead paragraphs

- teachers_digital_platform/crtool/src/__tests__/__snapshots__/app_test.js.snap
- teachers_digital_platform/crtool/src/js/components/distinctives/DistinctiveButton.js
- teachers_digital_platform/css/cf-enhancements/molecules/form-fields.less
- teachers_digital_platform/css/cf-enhancements/molecules/notifications.less
- teachers_digital_platform/css/organisms/dimension-selection-bar.less
Fix dimension selection bar and related styles.
- Active state to completed dimension selection buttons
- Spacing, height, font-weight, and transitions of dimension selection buttons
- @rrstoll 
> Fix dimension selection bar

- teachers_digital_platform/css/cf-enhancements/organisms/modals.less
Fix alignment of modal dialogs
- Styles for modal dialogs to center it on the screen.
- @rrstoll 
> Fix alignment of modal dialogs

- teachers_digital_platform/crtool/src/js/constants.js
- teachers_digital_platform/jinja2/teachers_digital_platform/crt-start.html
Update text for grade dropdown to sentence case
- Update text for grade dropdown to sentence case
- @rrstoll 
> Update text for grade dropdown to sentence case

- teachers_digital_platform/crtool/src/__tests__/__snapshots__/ContentElementaryCriterionPage.test.js.snap
- teachers_digital_platform/crtool/src/__tests__/__snapshots__/QualityCriterionPage.test.js.snap
- teachers_digital_platform/crtool/src/__tests__/__snapshots__/UtilityCriterionPage.test.js.snap
- teachers_digital_platform/crtool/src/js/components/pages/CriterionLinkWrapper.js
- teachers_digital_platform/css/cf-enhancements/atoms/button-headings.less
Fix criterion button links
- Markup and styles for criterion button links
- @rrstoll 
> Fix criterion button links

- teachers_digital_platform/crtool/src/__tests__/__snapshots__/ContentElementaryCriterionPage.test.js.snap
- teachers_digital_platform/crtool/src/__tests__/__snapshots__/EfficacyCriterionPage.test.js.snap
- teachers_digital_platform/crtool/src/__tests__/__snapshots__/QualityCriterionPage.test.js.snap
- teachers_digital_platform/crtool/src/__tests__/__snapshots__/UtilityCriterionPage.test.js.snap
- teachers_digital_platform/crtool/src/__tests__/__snapshots__/app_test.js.snap
- teachers_digital_platform/crtool/src/js/components/dialogs/SaveWorkModal.js
- teachers_digital_platform/crtool/src/js/components/dialogs/StartOverModal.js
- teachers_digital_platform/jinja2/teachers_digital_platform/crt-start.html
Fix markup  on getting started page.
> Fix start page

- teachers_digital_platform/css/cf-enhancements/base.less
> Fix responsive heading sizes

- teachers_digital_platform/crtool/src/js/components/criterion/CriterionAnswerArea.js
- teachers_digital_platform/crtool/src/js/components/criterion/CriterionComponent.js
- teachers_digital_platform/crtool/src/js/components/criterion/CriterionRow.js
- teachers_digital_platform/crtool/src/js/components/criterion/RadioButton.js
- teachers_digital_platform/crtool/src/js/components/pages/FinalPrintPage.js
- teachers_digital_platform/crtool/src/js/components/pages/partial_pages/PrintIntroComponent.js
- teachers_digital_platform/crtool/src/js/content_data/efficacyContent.js
- teachers_digital_platform/crtool/src/js/content_data/qualityContent.js
- teachers_digital_platform/jinja2/teachers_digital_platform/crt-base.html
Update markup for final print summary page. This work _does not_ include the content for the Content, Utility, Quality, or Efficacy section.
- Markup for the final summary print page.
- To see the final summary print page, fill out a dimension and click on the "Continue to summary" button, then click on "Final Summary" button, then click on "Final Print" button.
- @rrstoll 
> Update markup for final print summary page

- teachers_digital_platform/crtool/src/js/components/pages/content/ContentElementarySummaryPage.js
Added final content for elementary school summary page.  One question about the lead paragraph: there were two so I've set each paragraph up with class "lead-paragraph."  Tried adding double <br> tags to a single paragraph with that class, but react didn't seem to like it.  Your thoughts?
> Add content for elementary school summary

- teachers_digital_platform/crtool/src/__tests__/__snapshots__/ContentElementaryCriterionPage.test.js.snap
- teachers_digital_platform/crtool/src/__tests__/__snapshots__/QualityCriterionPage.test.js.snap
- teachers_digital_platform/crtool/src/__tests__/__snapshots__/UtilityCriterionPage.test.js.snap
- teachers_digital_platform/crtool/src/js/components/pages/EfficacyCriterionPage.js
- teachers_digital_platform/crtool/src/js/components/pages/EfficacySummaryPage.js
- teachers_digital_platform/crtool/src/js/components/pages/QualityCriterionPage.js
- teachers_digital_platform/crtool/src/js/components/pages/QualitySummaryPage.js
- teachers_digital_platform/crtool/src/js/components/pages/UtilityCriterionPage.js
- teachers_digital_platform/crtool/src/js/components/pages/UtilitySummaryPage.js
- teachers_digital_platform/crtool/src/js/components/pages/content/ContentElementaryCriterionPage.js
- teachers_digital_platform/crtool/src/js/components/pages/content/ContentHighCriterionPage.js
- teachers_digital_platform/crtool/src/js/components/pages/content/ContentMiddleCriterionPage.js
- teachers_digital_platform/crtool/src/js/components/pages/content/ContentMiddleSummaryPage.js
Added final content for middle school summary page.
> Add content for middle school summary

- teachers_digital_platform/crtool/src/js/components/pages/content/ContentHighSummaryPage.js
Adding final high school summary content
> Add content for high school summary

- teachers_digital_platform/crtool/src/js/components/pages/content/ContentMiddleCriterionPage.js
- teachers_digital_platform/crtool/src/js/content_data/contentMiddle.js
Adding final content to middle school print json page
Fixing some extra spaces on middle school criterion page
> Add middle school print content

- teachers_digital_platform/crtool/src/js/components/pages/FinalSummaryPage.js
Add content to final summary page
- Final content for final summary page.
- @rrstoll 
> Add content to final summary page

- teachers_digital_platform/crtool/src/js/components/pages/content/ContentHighCriterionPage.js
- teachers_digital_platform/crtool/src/js/content_data/contentHigh.js
Adding final content to high school print json file
Spacing fix to high school criterion page
> Add content to high school print page

- teachers_digital_platform/crtool/src/js/content_data/efficacyContent.js
Final content added for efficacy print json file
> Add content to efficacy print page

- teachers_digital_platform/crtool/src/js/content_data/contentElementary.js
- teachers_digital_platform/crtool/src/js/content_data/qualityContent.js
Adding final content to quality print json file
Note: quality-crt-text-optional text fields not added to this file (See 1.1.1, 1.1.3, 1.3.1, 1.3.2)
> Add content to quality print page

- teachers_digital_platform/crtool/src/__tests__/__snapshots__/UtilityCriterionPage.test.js.snap
- teachers_digital_platform/crtool/src/js/components/pages/UtilityCriterionPage.js
- teachers_digital_platform/crtool/src/js/content_data/utilityContent.js
Add final content to utility print json file
Fix spacing issue on utility criterion page
> Add content to utility print page

- teachers_digital_platform/crtool/src/__tests__/__snapshots__/ContentElementaryCriterionPage.test.js.snap
- teachers_digital_platform/crtool/src/__tests__/__snapshots__/EfficacyCriterionPage.test.js.snap
- teachers_digital_platform/crtool/src/__tests__/__snapshots__/QualityCriterionPage.test.js.snap
- teachers_digital_platform/crtool/src/__tests__/__snapshots__/UtilityCriterionPage.test.js.snap
- teachers_digital_platform/crtool/src/__tests__/__snapshots__/app_test.js.snap
- teachers_digital_platform/crtool/src/js/components/dialogs/SaveWorkModal.js
- teachers_digital_platform/crtool/src/js/components/dialogs/StartOverModal.js
> Fix modal dialog titles

- teachers_digital_platform/jinja2/teachers_digital_platform/crt-start.html
Fix modal title size on getting started page.
- Modal title from h4 to h3 size.
- @rrstoll 
> Fix modal title size

- teachers_digital_platform/crtool/src/__tests__/__snapshots__/ContentElementaryCriterionPage.test.js.snap
- teachers_digital_platform/crtool/src/__tests__/__snapshots__/EfficacyCriterionPage.test.js.snap
- teachers_digital_platform/crtool/src/__tests__/__snapshots__/QualityCriterionPage.test.js.snap
- teachers_digital_platform/crtool/src/__tests__/__snapshots__/UtilityCriterionPage.test.js.snap
- teachers_digital_platform/crtool/src/js/components/pages/EfficacyCriterionPage.js
- teachers_digital_platform/crtool/src/js/components/pages/QualityCriterionPage.js
- teachers_digital_platform/crtool/src/js/components/pages/UtilityCriterionPage.js
- teachers_digital_platform/crtool/src/js/components/pages/content/ContentElementaryCriterionPage.js
- teachers_digital_platform/crtool/src/js/components/pages/content/ContentHighCriterionPage.js
- teachers_digital_platform/crtool/src/js/components/pages/content/ContentMiddleCriterionPage.js
Fix italic text in survey pages.
- Markup on survey pages to remove italics from instructions.
- @rrstoll 
> Fix italic text

- teachers_digital_platform/crtool/src/js/components/pages/content/ContentMiddleCriterionPage.js
- teachers_digital_platform/crtool/src/js/content_data/contentMiddle.js
Edited criterion #5 title in survey and print files; notes number fixed.
> Edits to criterion title; note numbering

- teachers_digital_platform/crtool/src/__tests__/__snapshots__/UtilityCriterionPage.test.js.snap
- teachers_digital_platform/crtool/src/js/components/pages/UtilityCriterionPage.js
- teachers_digital_platform/crtool/src/js/content_data/utilityContent.js
Utility survey text edited, periods removed.
> Text changes set.

- teachers_digital_platform/crtool/src/__tests__/__snapshots__/EfficacyCriterionPage.test.js.snap
- teachers_digital_platform/crtool/src/js/components/pages/EfficacyCriterionPage.js
Removed relevant italic text from all three criteria
> Removing italics from various locations

- teachers_digital_platform/crtool/src/js/components/buttons/FinalSummaryButton.js
> Changing Summary to lowercase

- teachers_digital_platform/crtool/src/__tests__/__snapshots__/ContentElementaryCriterionPage.test.js.snap
- teachers_digital_platform/crtool/src/__tests__/__snapshots__/EfficacyCriterionPage.test.js.snap
- teachers_digital_platform/crtool/src/__tests__/__snapshots__/QualityCriterionPage.test.js.snap
- teachers_digital_platform/crtool/src/__tests__/__snapshots__/UtilityCriterionPage.test.js.snap
- teachers_digital_platform/crtool/src/__tests__/__snapshots__/app_test.js.snap
- teachers_digital_platform/crtool/src/js/components/dialogs/SaveWorkModal.js
Adding class to save link on SaveWorkModal js file
> Adding class to Save work link

- teachers_digital_platform/crtool/src/__tests__/__snapshots__/EfficacyCriterionPage.test.js.snap
- teachers_digital_platform/crtool/src/js/components/pages/EfficacyCriterionPage.js
- teachers_digital_platform/crtool/src/js/components/pages/partial.pages/EfficacyStudyComponent.js
Adding a-btn__no-line class to Review another and Close links
> Removing underline from Review another and Close links

- teachers_digital_platform/crtool/src/__tests__/__snapshots__/QualityCriterionPage.test.js.snap
- teachers_digital_platform/crtool/src/js/components/pages/QualityCriterionPage.js
- teachers_digital_platform/crtool/src/js/content_data/qualityContent.js
Fixing text
Adding indicator 1.4 and shifting 1.3.3
Adding indicator fixes to quality print file
> Text changes; adding indicator 1.4

- teachers_digital_platform/crtool/src/js/components/common/ViewEditResponseComponent.js
Adding class to "View or edit responses" links
> Adding a-btn__no-line class to certain links

- teachers_digital_platform/css/cf-enhancements/molecules/button-groups.less
Fix alignment of button groups.
- Alignment of button groups
- @rrstoll 
> Fix alignment of button groups

- teachers_digital_platform/crtool/src/__tests__/__snapshots__/QualityCriterionPage.test.js.snap
- teachers_digital_platform/crtool/src/js/components/pages/QualityCriterionPage.js
Add optional helper text to Quality survey text fields.
- Optional helper text to Quality survey text fields
- @rrstoll 
> Add optional helper text to Quality survey text fields

- teachers_digital_platform/css/organisms/dimension-selection-bar.less
Fix focus/hover styles for completed dimensions.
- Focus/hover styles for completed dimensions
- @rrstoll 
> Fix focus/hover styles for completed dimensions

- teachers_digital_platform/crtool/src/js/business.logic/summary/efficacyCalculationService.js
- teachers_digital_platform/crtool/src/js/components/CustomerReviewToolComponent.js
- teachers_digital_platform/crtool/src/js/components/buttons/SummaryButton.js
- teachers_digital_platform/crtool/src/js/components/common/ViewEditResponseComponent.js
- teachers_digital_platform/crtool/src/js/components/pages/EfficacyCriterionPage.js
These conclude the last of the critical bugs.  
- GH#32: Scroll to top of screen when click "Summary ... Button" or "View or Edit responses" link
- GH#58: Fix the last of the Efficacy Survey page, specifically Criterion 1 now shows green check when in a complete state
- Also fixed Efficacy Overall score not showing if it was "Strong" (Incorrectly comparing "large"==="strong"
- Verify the above Additions do what they say they do
- @dcmouyard 
> Fixed two more critical bugs GH#32, GH#58

- teachers_digital_platform/jinja2/teachers_digital_platform/crt-start.html
Add link to PDF download
- Link to PDF download
- @rrstoll 
> Add link to PDF download

- teachers_digital_platform/crtool/src/js/components/common/DimensionIconTitleComponent.js
- teachers_digital_platform/crtool/src/js/components/common/DimensionInformation.js
- teachers_digital_platform/crtool/src/js/components/common/DimensionNotReviewedComponent.js
- teachers_digital_platform/crtool/src/js/components/common/KeyTakeawaysComponent.js
- teachers_digital_platform/crtool/src/js/components/pages/ContentPrintElementaryPage.js
- teachers_digital_platform/crtool/src/js/components/pages/ContentPrintHighPage.js
- teachers_digital_platform/crtool/src/js/components/pages/ContentPrintMiddlePage.js
- teachers_digital_platform/crtool/src/js/components/pages/EfficacyPrintPage.js
- teachers_digital_platform/crtool/src/js/components/pages/FinalSummaryPage.js
- teachers_digital_platform/crtool/src/js/components/pages/QualityPrintPage.js
- teachers_digital_platform/crtool/src/js/components/pages/UtilityPrintPage.js
- teachers_digital_platform/crtool/src/js/components/pages/summary/ContentCriterionBlockSummary.js
- teachers_digital_platform/crtool/src/js/components/pages/summary/CriterionScoreBlock.js
- teachers_digital_platform/crtool/src/js/components/pages/summary/DimensionScoreBlock.js
- teachers_digital_platform/crtool/src/js/components/pages/summary/EfficacyCriterionBlockSummary.js
- teachers_digital_platform/crtool/src/js/components/pages/summary/QualityCriterionBlockSummary.js
- teachers_digital_platform/crtool/src/js/components/pages/summary/UtilityCriterionBlockSummary.js
Fix spacing on print pages.
- Markup on print pages to match the prototypes
- @rrstoll 
> Fix spacing on print pages

- teachers_digital_platform/crtool/src/js/components/pages/ContentPrintElementaryPage.js
- teachers_digital_platform/crtool/src/js/components/pages/ContentPrintHighPage.js
- teachers_digital_platform/crtool/src/js/components/pages/ContentPrintMiddlePage.js
- teachers_digital_platform/crtool/src/js/components/pages/content/ContentElementarySummaryPage.js
- teachers_digital_platform/crtool/src/js/components/pages/content/ContentHighSummaryPage.js
- teachers_digital_platform/crtool/src/js/components/pages/content/ContentMiddleSummaryPage.js
Removing benefical tag from all grades
> Removing beneficial from all three grades

- teachers_digital_platform/crtool/src/js/components/pages/summary/DimensionScoreBlock.js
Changed variable "moderate" to "moderateText"
> Tweak to variable name

- teachers_digital_platform/crtool/src/js/components/pages/EfficacySummaryPage.js
- teachers_digital_platform/crtool/src/js/components/pages/QualitySummaryPage.js
- teachers_digital_platform/crtool/src/js/components/pages/UtilitySummaryPage.js
- teachers_digital_platform/crtool/src/js/components/pages/content/ContentHighSummaryPage.js
- teachers_digital_platform/crtool/src/js/components/pages/content/ContentMiddleSummaryPage.js
Added missing sentence to high school, middle, utility, quality and efficacy summaries
> Adding missing sentence

- teachers_digital_platform/crtool/src/js/components/pages/QualitySummaryPage.js
- teachers_digital_platform/crtool/src/js/components/pages/UtilitySummaryPage.js
> Italics removed from quality and utility summary pages

- teachers_digital_platform/crtool/src/js/components/common/DimensionIconTitleComponent.js
Word added to DimensionIconTitleComponent.js file
> Adding word criterion after dimension title

- teachers_digital_platform/crtool/src/js/components/pages/ContentPrintElementaryPage.js
- teachers_digital_platform/crtool/src/js/components/pages/ContentPrintHighPage.js
- teachers_digital_platform/crtool/src/js/components/pages/ContentPrintMiddlePage.js
- teachers_digital_platform/crtool/src/js/components/pages/content/ContentElementaryCriterionPage.js
- teachers_digital_platform/crtool/src/js/components/pages/content/ContentElementarySummaryPage.js
- teachers_digital_platform/crtool/src/js/components/pages/content/ContentHighCriterionPage.js
- teachers_digital_platform/crtool/src/js/components/pages/content/ContentHighSummaryPage.js
- teachers_digital_platform/crtool/src/js/components/pages/content/ContentMiddleCriterionPage.js
- teachers_digital_platform/crtool/src/js/components/pages/content/ContentMiddleSummaryPage.js
> Small text changes

- teachers_digital_platform/crtool/src/js/components/pages/partial.pages/EfficacyOveralScoreComponent.js
Fix markup for efficacy score component on print pages.
- Markup for efficacy score component on print pages
- @rrstoll 
> Fix markup for efficacy score component on print pages

- teachers_digital_platform/crtool/src/js/components/pages/QualityPrintPage.js
- teachers_digital_platform/crtool/src/js/components/pages/UtilityPrintPage.js
- teachers_digital_platform/crtool/src/js/components/pages/summary/CriterionScoreBlock.js
Removing italics from utility print, quality print and criterionScoreBlock.js files
> Remove italics

- teachers_digital_platform/crtool/src/js/components/common/DimensionInformation.js
- teachers_digital_platform/crtool/src/js/components/pages/FinalCurriculumInformation.js
Fix order of labels on print pages.
- Order of labels on print pages
- @rrstoll 
> Fix order of labels on print pages

- teachers_digital_platform/crtool/src/js/components/pages/FinalSummaryPage.js
Fix markup on final summary page.
- Markup on final summary page
- @rrstoll 
> Fix markup on final summary page

- teachers_digital_platform/crtool/src/js/components/pages/summary/DimensionScoreBlock.js
Ticket #95.  Small tweak to variable name to pull in moderate supporting text
> Fixed "moderateText" variable name

- teachers_digital_platform/crtool/src/js/components/pages/partial.pages/EfficacyOveralScoreComponent.js
Ticket #73.  Created that empty pr before, assuming it was this work.  All well now.
> Adding text to efficacy score line

- teachers_digital_platform/crtool/src/__tests__/__snapshots__/app_test.js.snap
- teachers_digital_platform/crtool/src/js/components/CustomerReviewToolComponent.js
- teachers_digital_platform/crtool/src/js/components/pages/FinalSummaryPage.js
Case change to two files.  Ticket #101.
> Case change

- teachers_digital_platform/crtool/src/js/components/pages/summary/DimensionScoreBlock.js
Changing {this.props.dimensionPage} to lower case.
> Fix dimension summary label

- teachers_digital_platform/crtool/src/js/components/pages/content/ContentMiddleSummaryPage.js
- teachers_digital_platform/crtool/src/js/components/pages/summary/CriterionScoreBlock.js
Fix markup and content on middle school content summary.
- Markup and content on middle school content summary
> Fix markup and content on middle school content summary

- teachers_digital_platform/crtool/src/__tests__/__snapshots__/EfficacyCriterionPage.test.js.snap
- teachers_digital_platform/crtool/src/js/components/pages/EfficacyCriterionPage.js
Edited instruction text and changed button text in two locations
> GH 116 - changes to Efficacy instruction text and buttons

- teachers_digital_platform/crtool/src/js/components/pages/partial.pages/EfficacyOveralScoreComponent.js
Fixed now.  Edited 2 of 3 sets of labels the first time around.  Third set is correct now.
> GH 73 - tweaking efficacy labels

- teachers_digital_platform/crtool/src/js/components/pages/summary/DimensionScoreBlock.js
Discovered missing variables that needed toLowerCase() method
> GH 91 fixing summary labels

- teachers_digital_platform/crtool/src/js/components/pages/content/ContentElementarySummaryPage.js
- teachers_digital_platform/crtool/src/js/components/pages/content/ContentHighSummaryPage.js
Update criterion answer text for elementary and high school content.
- Criterion answer text for elementary and high school content
> Update criterion answer text for elementary and high school content

- teachers_digital_platform/crtool/src/__tests__/__snapshots__/ContentElementaryCriterionPage.test.js.snap
- teachers_digital_platform/crtool/src/__tests__/__snapshots__/EfficacyCriterionPage.test.js.snap
- teachers_digital_platform/crtool/src/__tests__/__snapshots__/QualityCriterionPage.test.js.snap
- teachers_digital_platform/crtool/src/__tests__/__snapshots__/UtilityCriterionPage.test.js.snap
- teachers_digital_platform/crtool/src/js/components/pages/EfficacyCriterionPage.js
- teachers_digital_platform/crtool/src/js/components/pages/QualityCriterionPage.js
- teachers_digital_platform/crtool/src/js/components/pages/UtilityCriterionPage.js
- teachers_digital_platform/crtool/src/js/components/pages/content/ContentElementaryCriterionPage.js
- teachers_digital_platform/crtool/src/js/components/pages/content/ContentHighCriterionPage.js
- teachers_digital_platform/crtool/src/js/components/pages/content/ContentMiddleCriterionPage.js
Update helper text on survey pages.
- Helper text on survey pages
> Update helper text on survey pages

- teachers_digital_platform/crtool/src/js/components/pages/partial.pages/EfficacyScopeEvidenceComponent.js
Fix spacing on efficacy print page.
- Spacing on efficacy print page
> Fix spacing on efficacy print page

- teachers_digital_platform/crtool/src/js/components/common/FinalCurriculumInformation.js
Add eyebrow to final summary print pages.
- Eyebrow to final summary print pages
> Add eyebrow to final summary print pages

- teachers_digital_platform/crtool/src/__tests__/__snapshots__/ContentElementaryCriterionPage.test.js.snap
- teachers_digital_platform/crtool/src/__tests__/__snapshots__/EfficacyCriterionPage.test.js.snap
- teachers_digital_platform/crtool/src/__tests__/__snapshots__/QualityCriterionPage.test.js.snap
- teachers_digital_platform/crtool/src/__tests__/__snapshots__/UtilityCriterionPage.test.js.snap
- teachers_digital_platform/crtool/src/js/components/pages/EfficacyCriterionPage.js
- teachers_digital_platform/crtool/src/js/components/pages/QualityCriterionPage.js
- teachers_digital_platform/crtool/src/js/components/pages/UtilityCriterionPage.js
- teachers_digital_platform/crtool/src/js/components/pages/content/ContentElementaryCriterionPage.js
- teachers_digital_platform/crtool/src/js/components/pages/content/ContentHighCriterionPage.js
- teachers_digital_platform/crtool/src/js/components/pages/content/ContentMiddleCriterionPage.js
Fix spacing on survey pages.
- Spacing on survey pages
> Fix spacing on survey pages

- teachers_digital_platform/crtool/src/__tests__/__snapshots__/EfficacyCriterionPage.test.js.snap
- teachers_digital_platform/crtool/src/js/components/pages/EfficacyCriterionPage.js
Update efficacy survey instructions.
- Efficacy survey instructions
- @rrstoll 
> Update efficacy survey instructions

- teachers_digital_platform/crtool/src/js/components/pages/partial.pages/EfficacyScopeEvidenceComponent.js
Update link to efficacy scoring guide pdf.
- Link to efficacy scoring guide pdf
- @rrstoll 
> Update link to efficacy scoring guide pdf

- teachers_digital_platform/jinja2/teachers_digital_platform/crt-start.html
Update PDF link on getting started page.
- PDF link on getting started page
- @rrstoll 
> Update PDF link on getting started page

- teachers_digital_platform/crtool/src/js/components/buttons/RadioButton.js
- teachers_digital_platform/crtool/src/js/components/buttons/RadioButtonEditable.js
- teachers_digital_platform/crtool/src/js/components/common/DimensionIconTitleComponent.js
- teachers_digital_platform/crtool/src/js/components/criterion/CriterionAnswerArea.js
- teachers_digital_platform/crtool/src/js/components/criterion/CriterionAnswerAreaEfficacyStudy.js
- teachers_digital_platform/crtool/src/js/components/criterion/CriterionComponent.js
- teachers_digital_platform/crtool/src/js/components/criterion/CriterionRow.js
- teachers_digital_platform/crtool/src/js/components/pages/summary/CriterionScoreBlock.js
- teachers_digital_platform/crtool/src/js/components/pages/summary/DimensionScoreBlock.js
Fix accessibility of pseudo-radio buttons.
- Markup using aria attributes for accessible pseudo-radio buttons
- @rrstoll 
> Fix accessibility of pseudo-radio buttons

- teachers_digital_platform/crtool/src/__tests__/__snapshots__/ContentElementaryCriterionPage.test.js.snap
- teachers_digital_platform/crtool/src/__tests__/__snapshots__/EfficacyCriterionPage.test.js.snap
- teachers_digital_platform/crtool/src/__tests__/__snapshots__/QualityCriterionPage.test.js.snap
- teachers_digital_platform/crtool/src/__tests__/__snapshots__/UtilityCriterionPage.test.js.snap
- teachers_digital_platform/crtool/src/js/components/pages/EfficacyCriterionPage.js
- teachers_digital_platform/crtool/src/js/components/pages/QualityCriterionPage.js
- teachers_digital_platform/crtool/src/js/components/pages/UtilityCriterionPage.js
- teachers_digital_platform/crtool/src/js/components/pages/content/ContentElementaryCriterionPage.js
- teachers_digital_platform/crtool/src/js/components/pages/content/ContentHighCriterionPage.js
- teachers_digital_platform/crtool/src/js/components/pages/content/ContentMiddleCriterionPage.js
- teachers_digital_platform/crtool/src/js/components/pages/partial.pages/EfficacyScopeEvidenceComponent.js
- teachers_digital_platform/jinja2/teachers_digital_platform/crt-start.html
Adding final urls.  Allen, you may have rerun the test snapshots for these pages.
> Adding final pdf urls on various pages

- teachers_digital_platform/css/organisms/dimension-selection-bar.less
Fix dimension selection buttons on mobile devices
- Mobile styles for dimension selection bar
> Fix dimension selection buttons on mobile devices

- teachers_digital_platform/crtool/src/js/components/common/PrintOrSaveFinalSummary.js
- teachers_digital_platform/css/cf-enhancements/molecules/button-groups.less
Add margin between buttons in button groups when collapsed
- Margin between buttons in button groups when collapsed
> Add margin between buttons in button groups when collapsed

- teachers_digital_platform/crtool/src/js/components/buttons/FinalSummaryButton.js
- teachers_digital_platform/crtool/src/js/components/distinctives/DistinctiveMenuBar.js
- teachers_digital_platform/css/cf-enhancements/atoms/button.less
Add active button variant for final summary button
- Active variant for buttons
> Add active button variant for final summary button

- teachers_digital_platform/search-urls.py
Created search-urls.py so we have something for our cfgov-refresh repo to point to once they turn on the search feature flag
@dcmouyard
> Created initial search-urls.py that wagtail parent will redirect too

- teachers_digital_platform/crtool/README.md
Initial README.md updates for crtool
- @dcmouyard 
> README.md updates for crtool

- teachers_digital_platform/css/cf-enhancements/base.less
Fix heading fonts.
- Heading styles.
> Fix heading fonts

- teachers_digital_platform/crtool/src/__tests__/__snapshots__/QualityCriterionPage.test.js.snap
- teachers_digital_platform/crtool/src/js/business.logic/criterionService.js
- teachers_digital_platform/crtool/src/js/business.logic/summary/criterionCalculationService.js
- teachers_digital_platform/crtool/src/js/components/CustomerReviewToolComponent.js
- teachers_digital_platform/crtool/src/js/components/dialogs/SaveWorkModal.js
- teachers_digital_platform/crtool/src/js/components/dialogs/StartOverModal.js
- teachers_digital_platform/crtool/src/js/components/pages/QualityCriterionPage.js
- teachers_digital_platform/crtool/src/js/components/pages/partial.pages/EfficacyStudyComponent.js
- teachers_digital_platform/jinja2/teachers_digital_platform/crt-start.html
Updated crt-start.html & the react app to conform to updates requested from the analytics team
- @dcmouyard
> Analytics followup

- teachers_digital_platform/crtool/src/js/components/CustomerReviewToolComponent.js
- teachers_digital_platform/crtool/src/js/components/dialogs/SaveWorkModal.js
- teachers_digital_platform/crtool/src/js/components/dialogs/StartOverModal.js
- teachers_digital_platform/jinja2/teachers_digital_platform/crt-start.html
- Fixed two issues with Analytics "Start over with a new review"
- @rrstoll 
> crtool-analytics: Fixing last two anlytic finds/issues

- teachers_digital_platform/crtool/package-lock.json
- teachers_digital_platform/crtool/src/js/components/dialogs/SaveWorkModal.js
- teachers_digital_platform/crtool/src/js/components/dialogs/StartOverModal.js
- teachers_digital_platform/jinja2/teachers_digital_platform/crt-start.html
- Fixed broken dialogs due to previous 508 compliance bug
- @rrstoll 
> modal-508: fixed modal 508 compliance

- teachers_digital_platform/crtool/src/__tests__/__snapshots__/ContentElementaryCriterionPage.test.js.snap
- teachers_digital_platform/crtool/src/__tests__/__snapshots__/ContentHighCriterionPage.test.js.snap
- teachers_digital_platform/crtool/src/__tests__/__snapshots__/EfficacyPrintPage.test.js.snap
- teachers_digital_platform/crtool/src/js/components/pages/EfficacyPrintPage.js
- teachers_digital_platform/crtool/src/js/components/pages/EfficacySummaryPage.js
- teachers_digital_platform/crtool/src/js/components/pages/FinalSummaryPage.js
- teachers_digital_platform/crtool/src/js/components/pages/content/ContentElementaryCriterionPage.js
- teachers_digital_platform/crtool/src/js/components/pages/content/ContentHighCriterionPage.js
- teachers_digital_platform/crtool/src/js/components/pages/partial.pages/EfficacyOveralScoreComponent.js
Fix field label associations.
- The `for` attribute on certain field labels.
- @rrstoll 
> Fix field label associations

- teachers_digital_platform/crtool/package-lock.json
- teachers_digital_platform/crtool/src/__tests__/__snapshots__/ContentElementaryCriterionPage.test.js.snap
- teachers_digital_platform/crtool/src/__tests__/__snapshots__/ContentHighCriterionPage.test.js.snap
- teachers_digital_platform/crtool/src/__tests__/__snapshots__/ContentMiddleCriterionPage.test.js.snap
- teachers_digital_platform/crtool/src/__tests__/__snapshots__/EfficacyCriterionPage.test.js.snap
- teachers_digital_platform/crtool/src/__tests__/__snapshots__/QualityCriterionPage.test.js.snap
- teachers_digital_platform/crtool/src/__tests__/__snapshots__/UtilityCriterionPage.test.js.snap
- teachers_digital_platform/crtool/src/js/components/pages/EfficacyCriterionPage.js
- teachers_digital_platform/crtool/src/js/components/pages/EfficacySummaryPage.js
- teachers_digital_platform/crtool/src/js/components/pages/QualityCriterionPage.js
- teachers_digital_platform/crtool/src/js/components/pages/QualitySummaryPage.js
- teachers_digital_platform/crtool/src/js/components/pages/UtilityCriterionPage.js
- teachers_digital_platform/crtool/src/js/components/pages/UtilitySummaryPage.js
- teachers_digital_platform/crtool/src/js/components/pages/content/ContentElementaryCriterionPage.js
- teachers_digital_platform/crtool/src/js/components/pages/content/ContentElementarySummaryPage.js
- teachers_digital_platform/crtool/src/js/components/pages/content/ContentHighCriterionPage.js
- teachers_digital_platform/crtool/src/js/components/pages/content/ContentHighSummaryPage.js
- teachers_digital_platform/crtool/src/js/components/pages/content/ContentMiddleCriterionPage.js
- teachers_digital_platform/crtool/src/js/components/pages/content/ContentMiddleSummaryPage.js
- teachers_digital_platform/crtool/src/js/components/pages/partial.pages/EditableCriterionRowWrapper.js
- teachers_digital_platform/crtool/src/js/components/pages/partial.pages/EfficacyStudyComponent.js
- teachers_digital_platform/crtool/src/js/components/pages/summary/CriterionScoreBlock.js
Fix heading levels on survey and summary pages.
- Heading levels on survey and summary pages.
- @rrstoll 
> Fix heading levels

- teachers_digital_platform/crtool/src/js/business.logic/criterionService.js
- teachers_digital_platform/jinja2/teachers_digital_platform/crt-start.html
- Updated start page to show not supported message if browser is IE8.  Message included a link to download the PDF
- Fixed small bug with error messaging when field level bugs are showing answering one missed field caused all errors to disappeared.
- @dcmouyard @rrstoll 
> IE8: added ie8 not supported message & Fixed Bug

- teachers_digital_platform/crtool/src/__tests__/__snapshots__/UtilityCriterionPage.test.js.snap
- teachers_digital_platform/crtool/src/js/components/pages/UtilityCriterionPage.js
- teachers_digital_platform/crtool/src/js/content_data/utilityContent.js
Update content in Utility section.
- Content in Utility section.
- @atuggle 
> Update content in Utility section

- setup.py
- teachers_digital_platform/crtool/package-lock.json
- teachers_digital_platform/fields.py
- teachers_digital_platform/jinja2/teachers_digital_platform/activity_page.html
- teachers_digital_platform/jinja2/teachers_digital_platform/base.html
- teachers_digital_platform/migrations/0001_initial.py
- teachers_digital_platform/migrations/0002_activitysubtopic.py
- teachers_digital_platform/migrations/0003_auto_20180702_1507.py
- teachers_digital_platform/migrations/0004_auto_20180703_0825.py
- teachers_digital_platform/migrations/0005_auto_20180703_0923.py
- teachers_digital_platform/migrations/0006_auto_20180704_0756.py
- teachers_digital_platform/migrations/0007_auto_20180704_0907.py
- teachers_digital_platform/models.py
- teachers_digital_platform/wagtail_hooks.py
This reverts commit 2c43e6f0bc98d2a8d3da8b2a964a60320d2e0a7b, reversing
changes made to 4751881af86ef485514638be40d8a7b93eeaf740.
Reintroduces Activity Search work
> Revert "Merge pull request #202 from cfpb/revert-tdp-105"

- teachers_digital_platform/jinja2/teachers_digital_platform/activity_page.html
Update markup for activity detail page.
- Markup for activity detail page
- @rrstoll 
- @nbucknor 
> Update markup for activity detail page

- teachers_digital_platform/fixtures/activity_data_for_tests.json
- teachers_digital_platform/fixtures/tdp_initial_data.json
- teachers_digital_platform/jinja2/teachers_digital_platform/activity_index_page.html
- teachers_digital_platform/models.py
- teachers_digital_platform/tests/models/test_activity_index_page.py
- teachers_digital_platform/tests/models/test_activity_page.py
- teachers_digital_platform/tests/test_fixtures.py
- teachers_digital_platform/tests/test_models.py
- teachers_digital_platform/tests/test_views.py
- teachers_digital_platform/wagtail_hooks.py
This PR includes adding the TDP_Search_Interface feature flag and the creation of the django model fixtures.
to run tests shell into python and execute the following:
%> python cfgov/manage.py test teachers_digital_platform
to load fixture data shell in and run the folowing:
%> python cfgov/manage.py loaddata tdp_initial_data.json
> Added feature flags,  fixtures and tests

- teachers_digital_platform/migrations/0008_auto_20180718_1428.py
- teachers_digital_platform/migrations/0009_auto_20180718_1442.py
- teachers_digital_platform/models.py
- teachers_digital_platform/wagtail_hooks.py
- Changed verbose name for ActivityPage and ActivityIndexPage to "TDP Activity page" and "TDP Activity search page"
- @atuggle @dcmouyard @chosak
> Setting a verbose name for ActivityPage and ActivityIndexPage

- teachers_digital_platform/migrations/0010_load_initial_data.py
Created a data migration to load the tdp_initial_data fixture.
@atuggle @chosak
> [TDP-138] Adding data migration to load initial model data

- setup.py
- Adding the missing tdp_initial_data.json file to the whl
> adding fixtures/tdp_initial_data.json to the whl

- teachers_digital_platform/crtool/package.json
- teachers_digital_platform/jinja2/teachers_digital_platform/activity_page.html
Fix activity detail page.
- Activity detail page template now extendslayout-2-1-bleedbar.html
- Add in correct breadcrumb links
- @nbucknor 
> Fix activity detail page

- teachers_digital_platform/jinja2/teachers_digital_platform/activity_index_page.html
- teachers_digital_platform/jinja2/teachers_digital_platform/activity_page.html
- teachers_digital_platform/models.py
Modifications to the Activity Search page
- Added javascript autosubmit for facets
- Added filters applied block
- Added working next and previous pagination buttons
> Update Search page template

- setup.py
- teachers_digital_platform/jinja2/teachers_digital_platform/activity_index_page.html
- teachers_digital_platform/search_indexes.py
- Added templates/* to package_data
- Updated filters applied to better match eregs markup
- Putting search index behind feature flag
- Removed extraneous reference to "fixtures/tdp_initial_data.json"
> Adding missing template/* files to setup.py and enforcing feature flags

- package-lock.json
- package.json
- teachers_digital_platform/jinja2/teachers_digital_platform/activity_index_page.html
- teachers_digital_platform/js/index.js
Add search interface JS.
- `js/index.js` which gets compiled to `static/tdp/js/tdp.js`
- Update versions of babel
- @nbucknor 
> Add search interface JS

- teachers_digital_platform/jinja2/teachers_digital_platform/activity_index_page.html
- teachers_digital_platform/jinja2/teachers_digital_platform/activity_search_facets_and_results.html
- teachers_digital_platform/js/search.js
Fixing filter tags on search page
> Fixing filter tags on search page

- teachers_digital_platform/jinja2/teachers_digital_platform/activity_index_page.html
- teachers_digital_platform/jinja2/teachers_digital_platform/activity_search_facets_and_results.html
- teachers_digital_platform/js/search.js
- teachers_digital_platform/models/pages.py
- Updated search to function without page load
- Reduced items per page to 5
- Removed unnecessary submit button from facets
> Tdp search tweaks

- setup.py
Another attempt to fix the wheel file so the search index template files are packaged.
> add activitypage_text.txt to wheel

- teachers_digital_platform/models/pages.py
Removing eval() from codebase.
> Remove eval from code

- teachers_digital_platform/models/pages.py
- teachers_digital_platform/search_indexes.py
Only published ActivityPage objects should appear in search results.
> Modify search queryset to hide unpublished activities

- teachers_digital_platform/jinja2/teachers_digital_platform/activity_index_page.html
Add breadcrumbs to search landing page
- Breadcrumbs to search landing page
- @nbucknor 
> Add breadcrumbs to search landing page

- teachers_digital_platform/css/organisms/tour.less
- teachers_digital_platform/css/tdp.less
- teachers_digital_platform/jinja2/teachers_digital_platform/bb-tool.html
Update content and styles for building block tour.
- Styles for the building block tour.
- Content for the building block tour.
- http://localhost:8000/practitioner-resources/youth-financial-education/learn-about-the-building-blocks/take-a-tour
- @rrstoll 
- We’ll add the illustrations and update the colors when they’re finalized.
> Building block tour

- setup.py
- teachers_digital_platform/fixtures/tdp_initial_data.json
fix the wheel file by adding the missing static image
> Adding missing static/tdp/img directory to wheel and fix tdp_initial_data.json

- teachers_digital_platform/jinja2/teachers_digital_platform/bb-tool.html
Update links on building block tool.
- Links
- @nbucknor 
> Update links on building block tool

- teachers_digital_platform/js/Analytics.js
- teachers_digital_platform/js/index.js
- teachers_digital_platform/js/search.js
- teachers_digital_platform/js/tdp-analytics.js
- teachers_digital_platform/js/util/EventObserver.js
Add custom analytics flags for TDP Search tool.
- You can uncomment line #20 of js/tdp-analytics.js
- @atuggle @dcmouyard 
- Modeled work after eRegs solution
> TDP search tool analytics

- teachers_digital_platform/css/organisms/tour.less
Fix scrolling section on tour page.
- @rrstoll 
> Fix scrolling section on tour page

- teachers_digital_platform/models/pages.py
Removing unnecessary variable to fix bug #261 
- Removed query_string variable
- @atuggle @Scotchester
> [TDP-261] Remove unnecessary creation of query_string variable

- teachers_digital_platform/css/organisms/tour.less
- teachers_digital_platform/jinja2/teachers_digital_platform/bb-tool.html
Update styles for building blocks tour page.
- @rrstoll 
> Update building blocks tour styles

- teachers_digital_platform/css/pages/tdp-activity-search.less
- teachers_digital_platform/jinja2/teachers_digital_platform/activity_search_facets_and_results.html
Added a skip link over the search facets
- @dcmouyard 
> Adding visually hidden skip link to jump over filters.

- teachers_digital_platform/css/pages/tdp-activity-search.less
- teachers_digital_platform/jinja2/teachers_digital_platform/activity_search_facets_and_results.html
> [TDP] Updating no results markup to be more in-line with eRegs.

- package-lock.json
- package.json
- teachers_digital_platform/js/scroll.js
- teachers_digital_platform/js/search-utils.js
- teachers_digital_platform/js/search.js
- teachers_digital_platform/js/tdp-analytics.js
- teachers_digital_platform/js/tdp-utils.js
- teachers_digital_platform/js/util/ajax-request.js
Fix IE11 related bugs
- replaced fetch function
- updated forEach function to use arrays instead of node lists
> Fix IE errors

- teachers_digital_platform/jinja2/teachers_digital_platform/activity_search_facets_and_results.html
- teachers_digital_platform/js/search.js
Miscellaneous tweaks to pagination
- adding data-gtm_ignore="true" property to pagination buttons
- Updating paginator to jump to #tdp-search-facets-and-results anchor
> added gtm ignore to pagination and other pagination tweaks

- teachers_digital_platform/js/search.js
Remove the functionality that automatically checked the parent filter if all child filters were checked.
This is so we can be more consistent with [CCDB](https://www.consumerfinance.gov/data-research/consumer-complaints/search/?from=0&product=Mortgage%E2%80%A2Other%20mortgage&product=Mortgage%E2%80%A2Conventional%20fixed%20mortgage&product=Mortgage%E2%80%A2Second%20mortgage&product=Mortgage%E2%80%A2Home%20equity%20loan%20or%20line%20of%20credit%20%28HELOC%29&product=Mortgage%E2%80%A2Reverse%20mortgage&product=Mortgage%E2%80%A2VA%20mortgage&product=Mortgage%E2%80%A2Other%20type%20of%20mortgage&product=Mortgage%E2%80%A2Home%20equity%20loan%20or%20line%20of%20credit&product=Mortgage%E2%80%A2Conventional%20home%20mortgage&product=Mortgage%E2%80%A2Conventional%20adjustable%20mortgage%20%28ARM%2 …
> Make nested checkboxes behaviour consistent with CCDB

- teachers_digital_platform/search_indexes.py
Removing feature flag on ActivityPageIndex() definition
- @atuggle
> [TDP] removing feature flag from Haystack search index definition file

- teachers_digital_platform/css/organisms/tour.less
Fix tour layout in IE10 by tweaking flexbox styles.
- @rrstoll 
> Fix tour layout in IE10

- teachers_digital_platform/css/organisms/tour.less
Provide sensible layout for browsers that do not support flexbox.
- @rrstoll 
> Tour layout for non-flexbox browsers

- teachers_digital_platform/css/molecules/search-hero.less
- teachers_digital_platform/css/pages/tdp-activity-search.less
Provide sensible layout for browsers that do not support flexbox.
- @rrstoll 
> Search landing page layout for non-flexbox browsers

- teachers_digital_platform/crtool/README.md
I updated the Content section to better outline how the content works and how to edit it.  Please let me know if you want more explanation. I took a screen shot of the updated content below, or you can just look at the changed files.
- @stephanieosan @nbucknor 
> TDP: CRTool Documentation updated Edit Content section

- teachers_digital_platform/jinja2/teachers_digital_platform/bb-tool.html
Update content of building blocks tool.
- @rrstoll 
> Update content of building blocks tool

- teachers_digital_platform/jinja2/teachers_digital_platform/activity_search_facets_and_results.html
Update footer content on search landing page.
- @nbucknor 
> Update footer content on search landing page

- teachers_digital_platform/__tests__/Analytics.test.js
- teachers_digital_platform/__tests__/index.test.js
- teachers_digital_platform/__tests__/search-utils.test.js
- teachers_digital_platform/__tests__/search.test.js
- teachers_digital_platform/__tests__/tdp-utils.test.js
- teachers_digital_platform/__tests__/util/behavior.test.js
- teachers_digital_platform/__tests__/util/dom-events.test.js
- teachers_digital_platform/__tests__/util/dom-traverse.test.js
- teachers_digital_platform/__tests__/util/standard-type.test.js
- teachers_digital_platform/__tests__/util/type-checkers.test.js
- teachers_digital_platform/js/util/simulate-event.js
- Copied tests over from eRegs
- Started on tests for search.js
- Replaced code Analytics.test.js with code from cfgov-refresh Analytics-spec.js
- npm run test-js
- @user
-<img width="906" alt="screen shot 2018-10-11 at 10 38 15 am" src="https://user-images.githubusercontent.com/2914091/46812119-08902480-cd42-11e8-9183-c7bb69939e69.png">
> Saving progress on JS tests (WIP)

- teachers_digital_platform/jinja2/teachers_digital_platform/bb-tool.html
Update content for building blocks journey page.
- @rrstoll 
> Update content for building blocks journey page

- teachers_digital_platform/jinja2/teachers_digital_platform/activity_page.html
Update Jump$tart text in activity sidebar.
- @rrstoll 
> Update Jump$tart text in activity sidebar

- teachers_digital_platform/jinja2/teachers_digital_platform/activity_search_facets_and_results.html
Update no results text for search interface landing page.
- @rrstoll 
> Update no results text for search interface landing page

- INSTALL.md
- README.md
Fixing typos and missing content in documentation
> [TDP] fixing typo in README.md file and updating INSTALL.md

- .travis.yml
This project supports both Python 2 and 3. The wheel it generates should do the same.
> Build universal (Python 2 & 3) wheel

- INSTALL.md
Better installation instructions reflecting the different ways people might run cfgov-refresh (virtualenv or Docker).
Thanks to @cfarm for motivating this change.
> Improve INSTALL instructions

- teachers_digital_platform/js/search.js
- teachers_digital_platform/js/tdp-analytics.js
- Track both the keyword and the results count and AJAX page reload
- @dcmouyard
> Tdp analytics tweaks

- teachers_digital_platform/css/organisms/tour.less
Remove inset scrolling on journey page when there is more than a full-page of content.
- CSS changes to the Tour organism
> Remove inset scrolling on journey page

- teachers_digital_platform/jinja2/teachers_digital_platform/bb-tool.html
- Change “Bureau of Consumer Financial Protection” to “Consumer Financial Protection Bureau”
> Update text on the journey page

- teachers_digital_platform/jinja2/teachers_digital_platform/activity_page.html
Fixing a typo on the Activity Detail page Legal Disclaimer
> [TDP] fix typo in the detail page Disclaimer

- package-lock.json
- package.json
- teachers_digital_platform/__tests__/search.test.js
- teachers_digital_platform/__tests__/tdp-analytics.test.js
- teachers_digital_platform/__tests__/util/ClearableInput.test.js
- teachers_digital_platform/crtool/package-lock.json
- teachers_digital_platform/css/pages/tdp-activity-search.less
- teachers_digital_platform/jinja2/teachers_digital_platform/activity_index_page.html
- teachers_digital_platform/js/search-utils.js
- teachers_digital_platform/js/search.js
- teachers_digital_platform/js/util/ClearableInput.js
- teachers_digital_platform/js/util/atomic-helpers.js
- Adds "Clear" button to keyword search field
- @dcmouyard
> TDP clear search button

- teachers_digital_platform/jinja2/teachers_digital_platform/activity_search_result.html
Remove the Age range field from Activity Search result template.
- Removed Age range from TDP Activity search results
> [TDP] remove Age range from search results

- teachers_digital_platform/tests/models/test_activity_index_page.py
- teachers_digital_platform/tests/models/test_activity_page.py
The model-mommy project was recently [renamed to model-bakery](https://model-bakery.readthedocs.io/en/latest/index.html#model-bakery-smart-fixtures-for-better-tests). Our version was also a little bit out of date. This change uses the new package name and brings it up to date.
Tests for this PR won't pass until cfgov-refresh is updated in https://github.com/cfpb/cfgov-refresh/pull/5601.
> Replace use of model-mommy with model-bakery

- setup.py
Update Django from 2.0 to 2.2
- tox -e unittest-current
- tox -e unittest-future
> Support Django 2.2

- crtool/jinja2/crtool/crt-start.html
Update the link to the CR Tool checklist PDF.
---
- Change link to the CR Tool checklist PDF
> Update link to CR Tool Checklist PDF

- package-lock.json
- package.json
- src/__tests__/crtoolLocalStorage/cancelSaveIfDirty.test.js
- src/__tests__/crtoolLocalStorage/clear.test.js
- src/__tests__/crtoolLocalStorage/fetchReviewFromServer.test.js
- src/__tests__/crtoolLocalStorage/getHref.test.js
- src/__tests__/crtoolLocalStorage/getItem.test.js
- src/__tests__/crtoolLocalStorage/init_test.js
- src/__tests__/crtoolLocalStorage/isReady.test.js
- src/__tests__/crtoolLocalStorage/isValidReview.test.js
- src/__tests__/crtoolLocalStorage/loadReviewFromLocalStorage.test.js
- src/__tests__/crtoolLocalStorage/removeItem.test.js
- src/__tests__/crtoolLocalStorage/saveIfDirty.test.js
- src/__tests__/crtoolLocalStorage/saveReviewToLocalStorage.test.js
- src/__tests__/crtoolLocalStorage/saveReviewToServer.test.js
- src/__tests__/crtoolLocalStorage/setHref.test.js
- src/__tests__/crtoolLocalStorage/setItem.test.js
- src/__tests__/crtoolLocalStorage/setUrlToken.test.js
- src/crtoolLocalStorage.js
Adding more unit test coverage for crtoolLocalStorage.js.
> Crtool local storage unit tests

- src/crtoolLocalStorage.js
- src/js/components/dialogs/AccessCodeModal.js
The original Access code Modal text wasn't descriptive enough, so it will need to change from this:
> The access code is unique to this review. To return to a review you have already started, you need to save this code.
to this:
> The access code is unique to this review. To return to a review you have already started, you will need this code. Please either bookmark this page, or copy and save the code in your personal files.
---
> Change access code modal text

- README.md
> Update app URLs in README

- setup.py
- tox.ini
Prepping for Django 3.2
---
-
-
-
1.
-
Visually tested in the following supported browsers:
> Support Django 3.2

- .github/workflows/ci.yml
- tox.ini
This change updates our base Python required to 3.8.
> Update to Python 3.8
