- .gitignore
- satellite/jinja2/satellite/base.html
- satellite/urls.py
Let's get this thing actually running in cfgov-refresh!
- An empty base template
- `urls.py` to make it accessible once installed in a parent project
- Adds `.eggs/` to `.gitignore`.
1. Clone repo as sibling of cfgov-refresh
1. Back in cfgov-refresh's directory, `pip install -e ../django-satellite-app/`
1. Add `{'import': 'satellite', 'apps': ('satellite',)},` to `OPTIONAL_APPS` in `cfgov/cfgov/settings/base.py`
1. Add `url(r'^satellite/', include_if_app_enabled('satellite', 'satellite.urls')),` to `urlpatterns` in `cfgov/cfgov/urls.py`
1. `./runserver.sh`
1. Visit http://localhost:8000/satellite/
> Add a base template to build off of

- satellite/admin.py
- satellite/models.py
- satellite/tests.py
- satellite/tests/settings.py
- satellite/tests/test_models.py
- satellite/tests/test_views.py
- satellite/urls.py
- satellite/views.py
- setup.py
- tox.ini
This PR adds a skeleton setup for unit tests, a tox environment based on the documentation and examples in https://github.com/cfpb/development/pull/154.
> Add tox, flake8, isort, and test skeleton

- satellite/jinja2/satellite/base.html
This PR fleshes out the base template so that it has all of the main blocks needed to start creating page templates for the satellite app.
- Lots of Jinja template blocks with default stuff in them
1. Clone repo as sibling of cfgov-refresh
1. Back in cfgov-refresh's directory, `pip install -e ../django-satellite-app/`
1. Add `{'import': 'satellite', 'apps': ('satellite',)},` to `OPTIONAL_APPS` in `cfgov/cfgov/settings/base.py`
1. Add `url(r'^satellite/', include_if_app_enabled('satellite', 'satellite.urls')),` to `urlpatterns` in `cfgov/cfgov/urls.py`
1. `./runserver.sh`
1. Visit http://localhost:8000/satellite/
> Update base template to include necessary blocks

- tox.ini
There's a slight mistake I made when pasting from the [dev standards isort config](https://github.com/cfpb/development/blob/master/.isort.cfg) into the tox.ini file — the isort section needs to be named "`isort`" here.
> Correct paste-error in isort settings

- .stylelintrc
- gulp/config.js
- gulp/tasks/lint.js
- gulp/webpack-config.js
- package-lock.json
- package.json
- teachers_digital_platform/css/tdp.less
This will make it easier for the TDP developers to stay consistent with our style. Rules are based on what Adam added to the initial capital-framework PR, with a few additions that I thought would be useful. We could probably add a whole lot more rules, too, but I'll save that for a PR to cfpb/development.
Paired on this with @jimmynotjim.
- Stylelint config file and `gulp lint:styles` task
- `gulp lint:build` task to lint the Gulp scripts
- Added importing of Capital Framework Less files by reference so that the app's Less files have access to CF's variables and mixins, but it won't duplicate the CF CSS output
1. `npm install`
1. `gulp lint` to run the whole suite of Linters, or `gulp lint:build`, `gulp lint:tests`, `gulp lint:scripts`, and `gulp lint:styles` to run them individually
1. …
> Set up Stylelint and fix CF importing

- package-lock.json
- package.json
Low severity as this is just a devdep, but this'll get the big yellow notice off.
> Updates jsdoc to no longer depend on a vulnerable package

- .eslintrc
- gulp/config.js
- gulp/tasks/lint.js
gulp-eslint was throwing errors in this repo when cloned within `cfgov-refresh/develop-apps/` due to a version mismatch between the version of ESLint used here and the later version used in cfgov-refresh. This PR tells ESLint to not use its default behavior of looking up the tree for additional `.eslintrc` files.
It also fixes the `lint:tests` subtask so that it actually finds the files.
- `root: true` rule in `.eslintrc`
- `lint:tests` now uses `config.lint.tests` as its `src`, for consistency with the other tasks, and because its previous configuration was not finding the JS test files.
1. Pull branch to teachers-digital-platform clone within `cfgov-refresh/develop-apps/`
2. Run `gulp` or `gulp lint`
3. Observe no errors.
> Tell ESLint not to look up the tree for more .eslintrc files

- gulp/config.js
- gulp/tasks/styles.js
- package-lock.json
- package.json
Replaces gulp-changed with gulp-less to allow us to check the timestamp of `tdp.css` against all source files that could affect the output of `tdp.css`.
- gulp-newer for more robust determination of the necessity of building the Less files
- A bunch of unused modules in `styles.js`
- Linting fixes and standardization in `styles.js`
1. Pull this branch and `npm install`
2. Run `gulp clean` to clean everything out, then `gulp styles` for a baseline build.
3. Note time shown for `Finished 'styles:modern' after ____`
4. Run `gulp styles` again
5. Note that the time shown for `Finished 'styles:modern' after ____` is much much smaller. Styles were not built as gulp-newer did not detect any changes since the last update of the output `tdp.css` file.
6. Make a change in one of the new Less files, …
> Fix styles task not building when tdp.less is not updated

- teachers_digital_platform/css/cf-enhancements.less
- teachers_digital_platform/css/cf-enhancements/organisms/modals.less
- teachers_digital_platform/jinja2/teachers_digital_platform/prototypes/crt-start.html
Update markup and styles for the getting started prototype page for Curriculum Review tool to match the design.
- Styles for for new atoms, molecules, organisms, and utilities.
- Demo JavaScript to preview modal window functionality.
- Updated markup on the getting started page.
- @rrstoll 
- The getting started prototype page is at http://0.0.0.0:8000/tdp/prototypes/crt-start/
> Theme crt getting started

- .travis.yml
I *think* this will let the Travis wheel-building capture the static assets.
We can test with a new release.
> move wheel build step later in sequence

- teachers_digital_platform/css/molecules/component-list.less
- teachers_digital_platform/css/molecules/curriculum-status.less
- teachers_digital_platform/css/organisms/survey.less
- teachers_digital_platform/css/tdp.less
- teachers_digital_platform/jinja2/teachers_digital_platform/prototypes/crt-summary.html
Update markup and styles for the main content of the summary prototype page for Curriculum Review tool to match the design.
- Updated markup for the main content are of the summary page.
- @rrstoll 
- The summary prototype page is at http://0.0.0.0:8000/tdp/prototypes/crt-summary/
> Theme crt summary

- package-lock.json
- teachers_digital_platform/css/cf-enhancements/atoms/icon-svg.less
- teachers_digital_platform/css/tdp.less
- teachers_digital_platform/css/temp/cf-icons.less
This should stop Django's collectstatic process from looking for the old cf-icons fonts.
- Temporary manual copy of `.cf-icon-svg` styles
- Unused enhancements file which was throwing an error when I ran Gulp
- `package-lock.json` updated itself to change an http URL to https
1. Pull branch
1. Run `gulp`
1. View http://localhost:8000/tdp/prototypes/crt-survey/ and see the icons still there
Then we'll have to merge this, create a new release, update the version in cfgov-refresh, and see if that fixes the build.
> Manually bring in .cf-icon-svg Less to remediate collectstatic breakage

- teachers_digital_platform/crtool/src/__tests__/__snapshots__/ContentElementaryCriterionPage.test.js.snap
- teachers_digital_platform/crtool/src/__tests__/__snapshots__/EfficacyCriterionPage.test.js.snap
- teachers_digital_platform/crtool/src/__tests__/__snapshots__/QualityCriterionPage.test.js.snap
- teachers_digital_platform/crtool/src/__tests__/__snapshots__/UtilityCriterionPage.test.js.snap
- teachers_digital_platform/crtool/src/__tests__/__snapshots__/app_test.js.snap
- teachers_digital_platform/crtool/src/js/components/dialogs/SaveWorkModal.js
- teachers_digital_platform/crtool/src/js/components/dialogs/StartOverModal.js
- teachers_digital_platform/jinja2/teachers_digital_platform/crt-start.html
The two modal dialogs we have were interfering with each other because they were accidentally using each others functions.
- Duplicated the JavaScript functions that handles the click outside for the Modal Dialogs
- This was performed twice
- On the Start page in pure JavaScript
- On the Survey pages (in the dialogs/ folder)
- Load the start page and verify
- Load any of the survey pages
- @dcmouyard 
> Fixed Modal dialogs interfering with each other

- teachers_digital_platform/crtool/src/js/components/pages/QualitySummaryPage.js
- teachers_digital_platform/css/cf-enhancements/molecules/form-fields.less
- teachers_digital_platform/css/layout/survey-top.less
Fix summary page content and styles
- Icon for edit links
- Active/inactive state for radio text
- Left margin on `l-survey-top`
- Criterion headings now look like h2
- @rrstoll 
> Fix summary page content and styles

- teachers_digital_platform/crtool/src/js/components/CustomerReviewToolComponent.js
- teachers_digital_platform/crtool/src/js/components/criterion/CriterionAnswerArea.js
- teachers_digital_platform/crtool/src/js/content_data/utilityContent.js
Implemented a CONDITIONAL on printing html styling inline with print criterion content
- Added flag "hasInlineHtml" to the json content in order to use the 'dangerouslySetInnerHTML()' method when rendering the content
-  There is an example of this in the ".../content_data/utilityContent.js" file.  See the screen shot
- @dcmouyard @rrstoll 
> Implemented conditional for inline styling with json content

- teachers_digital_platform/crtool/src/__tests__/__snapshots__/EfficacyCriterionPage.test.js.snap
- teachers_digital_platform/crtool/src/js/components/CustomerReviewToolComponent.js
- teachers_digital_platform/crtool/src/js/components/buttons/SummaryButton.js
- teachers_digital_platform/crtool/src/js/components/pages/EfficacyCriterionPage.js
- teachers_digital_platform/crtool/src/js/components/pages/EfficacySummaryPage.js
- teachers_digital_platform/crtool/src/js/components/pages/QualitySummaryPage.js
- teachers_digital_platform/crtool/src/js/components/pages/UtilitySummaryPage.js
- teachers_digital_platform/crtool/src/js/components/pages/content/ContentElementarySummaryPage.js
- teachers_digital_platform/crtool/src/js/components/pages/content/ContentHighSummaryPage.js
- teachers_digital_platform/crtool/src/js/components/pages/content/ContentMiddleSummaryPage.js
Implemented Efficacy Summary page with stylings and correct calculations.  Also fixed the button enabling on the Efficacy Survey page
- Implemented Efficacy Summary page
- Fixed Efficacy Survey page button enablings
- "I'm done adding studies" always enabled (till you click it)
- "Continue to Summary" enabled once "I'm done adding studies" is clicked
- If two strong studies exist when clicking "I'm done adding studies" you see Criterion 2.  If not you see a green warning saying you can continue to summary
- @dcmouyard 
> Fix efficacy summary markup

- teachers_digital_platform/css/organisms/dimension-selection-bar.less
Fix dimension selection button styles for Safari.
- Styles for dimension selection buttons.
- @rrstoll 
> Fix dimension selection button styles for Safari

- teachers_digital_platform/crtool/src/js/business.logic/summary/contentElementaryCalculationService.js
- teachers_digital_platform/crtool/src/js/business.logic/summary/contentHighCalculationService.js
- teachers_digital_platform/crtool/src/js/business.logic/summary/contentMiddleCalculationService.js
- teachers_digital_platform/crtool/src/js/components/pages/ContentPrintElementaryPage.js
- teachers_digital_platform/crtool/src/js/components/pages/ContentPrintHighPage.js
- teachers_digital_platform/crtool/src/js/components/pages/ContentPrintMiddlePage.js
- teachers_digital_platform/crtool/src/js/components/pages/PrintAndSummaryPages.js
- teachers_digital_platform/crtool/src/js/components/pages/summary/CriterionScoreBlock.js
Since the CONTENT for print score is different between the different Content print pages I renamed ContentPrintPage.js to ContentPrintElementaryPage.js and duplicated it for Middle and High.
You will now find the following three files (currently identical)
- ContentPrintElementaryPage.js
- ContentPrintMiddlePage.js
- ContentPrintHighPage.js
If you direct me in the direction where I can find the content for the Content Score, I will update the two new ones.
- Created the following new files for Printing content scores
- ContentPrintElementaryPage.js 
- ContentPrintMiddlePage.js 
- ContentPrintHighPage.js
- Removed console.log() statements
- Fixed minor content score calculation error (Didn't affect the score, just threw and exception that got ignored
- Removed dead code in …
> Fix content print page

- teachers_digital_platform/css/organisms/dimension-selection-bar.less
Fix dimension selection bar layout.
- Add `clear: both` to dimension selection bar
- @rrstoll 
> Fix dimension selection bar layout

- teachers_digital_platform/crtool/src/js/components/pages/summary/CriterionScoreBlock.js
I think this remove any references to Essential from the content criteria.
> Fixes to several misspelled variable names

- teachers_digital_platform/crtool/package.json
- teachers_digital_platform/crtool/src/__tests__/__snapshots__/EfficacyCriterionPage.test.js.snap
- teachers_digital_platform/crtool/src/js/components/buttons/SummaryButton.js
- teachers_digital_platform/crtool/src/js/components/pages/EfficacyCriterionPage.js
- teachers_digital_platform/crtool/src/js/components/pages/QualityCriterionPage.js
- teachers_digital_platform/crtool/src/js/components/pages/SurveyPageContainer.js
- teachers_digital_platform/crtool/src/js/components/pages/UtilityCriterionPage.js
- teachers_digital_platform/crtool/src/js/components/pages/content/ContentElementaryCriterionPage.js
- teachers_digital_platform/crtool/src/js/components/pages/content/ContentHighCriterionPage.js
- teachers_digital_platform/crtool/src/js/components/pages/content/ContentMiddleCriterionPage.js
- teachers_digital_platform/crtool/src/js/components/pages/partial.pages/EfficacyStudyScoreComponent.js
- teachers_digital_platform/jinja2/teachers_digital_platform/crt-base.html
- teachers_digital_platform/jinja2/teachers_digital_platform/crt-start.html
- GH#103: 
- Manually versioned the javascript reference crtool.react.v1.js to fix this random issue
- GH#117: 
- Added new orange Notification to Efficacy page notifying user they still have required fields to populate
- GH#14:
- On start page, each keypress in the Curriculum Title triggers enabling of "Begin Review" if Grade has been populated
- GH#109: 
- Fixed bolded text on the Efficacy study score when score is week
- GH#25: 
- Removed Horizontal line above summary button if Summary button is enabled
- @dcmouyard 
> Fixed 5 more bugs

- teachers_digital_platform/jinja2/teachers_digital_platform/crt-start.html
Changed how crt-start page populates the dropdown since IE 10 and below do not like how I do it.
- See description
- @dcmouyard 
> IE.10: fixed start page not loading dropdowns

- teachers_digital_platform/crtool/src/__tests__/__snapshots__/EfficacyCriterionPage.test.js.snap
- teachers_digital_platform/crtool/src/__tests__/__snapshots__/QualityCriterionPage.test.js.snap
- teachers_digital_platform/crtool/src/__tests__/__snapshots__/UtilityCriterionPage.test.js.snap
- teachers_digital_platform/crtool/src/js/components/pages/EfficacyCriterionPage.js
- teachers_digital_platform/crtool/src/js/components/pages/QualityCriterionPage.js
- teachers_digital_platform/crtool/src/js/components/pages/UtilityCriterionPage.js
Fix typo on efficacy, quality, and utility survey pages.
- Fix typo on efficacy, quality, and utility survey pages
- @rrstoll 
> Fix typo on efficacy, quality, and utility survey pages

- teachers_digital_platform/css/organisms/survey.less
Adding max-width: 100% fixes the issue on the survey and print pages and doesn't affect Chrome.
> GH136: Adding max-width to fix IE11 bug

- setup.py
Closes #167.
This PR removes the wagtail requirement from `install_requires` in setup.py. This will resolve the version conflict with cfgov-refresh and allow tests that include optional apps in cfgov-refresh (like `tox -e validate-assets`) to run without erring.
- wagtail from `install_requires`
> Remove Wagtail from install_requires

- teachers_digital_platform/crtool/src/js/components/CustomerReviewToolComponent.js
- teachers_digital_platform/crtool/src/js/components/common/ViewEditResponseComponent.js
- teachers_digital_platform/jinja2/teachers_digital_platform/crt-start.html
Updated google analytics to match what the analytics team is asking for. 
Specifically made the following changes:
- Start Page
- On Submit, if Date not provided use "unspecified"
- Any button/link clicks got reworked to specify "button clicked: ..." or "link clicked: ..."
- Updated button/link clicks inside the start over modal 
- Survey tool updates
- Changed label for "view or edit responses" 
- Fixed Notes and Text fields that were still reporting as criterion radio button.
- Fixed label " I\'m done reviewing studies" to no have the escape \ in it
##Reviewers
- @dcmouyard @rrstoll 
#Testing 
- The only way to test locally is to toggle this flag in the constants file and look for console.log()'s
- ANALYTICS_DEBUG_ON = true
> crtool-analytics: final additions and fixes

- gulp/tasks/crtool.js
- gulp/tasks/test.js
Updated the gulp build and gulp test tasks for crtool, to use one command to execute them for the crtool.
Previously I had a task to cd down into the crtool folder and then one to cd back out.  The new code executes it in the subfolder with out having to cd.
This is much cleaner and removes any parallel execution issues.
> Updated gulp task to run one command, not 3 parallel commands

- setup.py
Something has changed and `bdist_wheel` apparently is now honoring this value, which is giving us a value we actually _don't_ want.
> Set version_format to what we want

- teachers_digital_platform/crtool/package-lock.json
- teachers_digital_platform/crtool/package.json
Turns out cfgov-refresh upgraded jest in the package.json.  Somehow that negatively affected jest in this repository.  Removed ^ from jest versioning to fix running test.
- updated jest version in package.json
- run "gulp test" after ensuring cfgov-repository node_modules has been installed
- @Scotchester @dcmouyard @rrstoll @willbarton @higs4281 
> FixBuild: Hard set jest version, so parent repos do not negatively affect

- teachers_digital_platform/crtool/src/__tests__/__snapshots__/EfficacyPrintPage.test.js.snap
- teachers_digital_platform/crtool/src/__tests__/__snapshots__/QualiyPrintPage.test.js.snap
- teachers_digital_platform/crtool/src/__tests__/__snapshots__/UtilityPrintPage.test.js.snap
- teachers_digital_platform/crtool/src/js/components/common/DimensionInformation.js
- teachers_digital_platform/crtool/src/js/components/common/FinalCurriculumInformation.js
Change CFPB to BCFP on summary pages
- Change CFPB to BCFP on summary pages
- @atuggle 
- @rrstoll 
> Change CFPB to BCFP on summary pages

- .travis.yml
- setup.py
This change reverts #186 and restores the use of detailed (dirty) release version formatting.
@contolini, @Scotchester and I debugged this on the [cfpb/retirement](https://github.com/cfpb/retirement) repo and determined that the unexpected version numbers are due to the frontend script changing the `package-lock.json` file.
See https://github.com/cfpb/retirement/pull/227 for the PR that fixed this on the retirement repo.
See https://travis-ci.org/chosak/teachers-digital-platform/jobs/407162397 for an example Travis build (on my fork) demonstrating that this works to properly name the built wheel. In this example, I've made a tag on my fork of [1.0.5](https://github.com/chosak/teachers-digital-platform/releases/tag/1.0.5). Travis then builds the wheel with the correct name …
> Restore detailed tag version format

- setup.py
- teachers_digital_platform/fixtures/tdp_updated_council_for_ed_data.json
- teachers_digital_platform/migrations/0011_update_initial_data.py
- teachers_digital_platform/migrations/0014_update_building_blocks.py
Updated migration 0011 to use it's own fixture file instead of reusing the tdp_initial_data.json fixture
> Update migrations so jenkins doesn't fail on 0011_update_initial_data

- teachers_digital_platform/migrations/0016_auto_20180829_2323.py
Set id_seq values to the max id value of the model table, so errors aren't thrown when trying to create a new records using django's admin UI.
> TDP Fixing sequence id numbers for django model tables

- tox.ini
This PR adds testing against Django 1.11 as part of the Tox matrix, as a new environment factor (`dj{18,111}`). Due to recent work on cfgov-refresh it is now possible to run and pass all unit tests there against Django 1.11.
- `tox`
> Add unit testing against Django 1.11

- teachers_digital_platform/jinja2/teachers_digital_platform/activity_index_page.html
- teachers_digital_platform/jinja2/teachers_digital_platform/activity_page.html
- teachers_digital_platform/jinja2/teachers_digital_platform/activity_search_facets_and_results.html
Update how SVGs are embedded into templates.
- Use template tags instead of hard-coded SVGs
- @rrstoll 
> SVG embeds

- teachers_digital_platform/jinja2/teachers_digital_platform/activity_search_facets_and_results.html
Removed a remaining reference to special-population that caused the student characteristics facet to function erratically.
- @atuggle
> fix lingering reference to special-population

- teachers_digital_platform/jinja2/teachers_digital_platform/activity_page.html
-
- Removing wrapper div around download links within Downloads .o-well
-
-
- @dcmouyard
-
-
> Removing link wrapper within o-well

- teachers_digital_platform/jinja2/teachers_digital_platform/activity_page.html
Wrapped the legal information divs in a .block div with the top margin set to zero.  Saw this on localhost:8000/practitioner-resources/youth-financial-education/.
> Wrapping legal info in .block div with no top margin

- teachers_digital_platform/css/cf-enhancements/molecules/form-fields.less
- teachers_digital_platform/css/molecules/form-fields.less
- teachers_digital_platform/css/tdp.less
- teachers_digital_platform/jinja2/teachers_digital_platform/activity_page.html
Edits to Activity detail page Download activity block (H3 tags given h6 styling at mobile widths; adjustments to the Download block's bottom padding values at mobile and desktop widths.
Note:  the wrapper div around the download links with class .u-mb30 was removed in PR #247.
> Activity detail sidebar tweaks

- .travis.yml
As a follow-up to #213, this fixes dirty wheel names as built by Travis. Moving the disabling of `package-lock.json` up better prevents creation of that file. Without changes to that file, the local git workspace looks cleaner, allowing for proper build wheel names.
See https://travis-ci.org/chosak/teachers-digital-platform/jobs/428793415 for a Travis release wheel build on my fork that successfully build a wheel named `teachers_digital_platform-1.0.5` -- ignore the error at the end due to an expected GH upload failure.
> Fix dirty Travis wheel names

- teachers_digital_platform/fixtures/tdp_initial_data.json
- teachers_digital_platform/models/pages.py
- teachers_digital_platform/tests/models/test_activity_index_page.py
- teachers_digital_platform/tests/models/test_pages_utilities.py
Removed RoutablePageMixin and Implemented initial Search page Unit Test using tox.  
Reasons for this are listed below in Additions:
1. When rendering the page from a unit test, using page.serve(...) or client.get(...) the search method was because they both use the serve(...) which then calls get_context(...) skipping the part where we add facets to the context so the template would fail to load because it depends on the facets
- See wagtail documentation on page.serve(...) here (as mentioned above): https://github.com/wagtail/wagtail/blob/master/wagtail/core/models.py#L716
- Since serve invokes both get_template & get_context, this appears to be the recommended way to implement the business logic for a view
2. I implemented 2 unit test one that renders the search index page …
> TDP: Implemented UnitTest and removed RoutablePageMixin

- teachers_digital_platform/js/scroll.js
Fix location of scrolling target so that the illustration is always at the top.
- @rrstoll 
> Fix location of scrolling target

- teachers_digital_platform/jinja2/teachers_digital_platform/activity_search_facets_and_results.html
- teachers_digital_platform/models/pages.py
Updating results count format to match:
> Desired syntax for results
> Default display: [x] activities (where x is the total number of activities currently in wagtail)
> Filtered display: Showing [y] matches of [x] activities (where y is the number of results based on the user filters / search)
> Update TDP search tool's results count format

- tox.ini
This change dumps the Python test coverage report to console after the tests run.
- Run `tox`, you'll see the test coverage report gets printed out.
> Print coverage report after running tests

- teachers_digital_platform/templates/search/indexes/teachers_digital_platform/activitypage_text.txt
Adding all Activity page fields to elasticsearch for keyword search
- updated activitypage_text.txt to include all activity page fields
- After updating the search index, `./cfgov/manage.py update_index -r teachers_digital_platform`, try to search for text that exists in any of those fields.
- @atuggle
> [TDP] Add all fields to keyword search

- teachers_digital_platform/js/search.js
- teachers_digital_platform/js/util/dom-traverse.js
Updating clear filter functionality to match eRegs. This fixes bugs in IE11 where the Clear Filter tags and Clear all filters link would throw JS errors.
> [TDP] Fix clear filter tags in IE11

- teachers_digital_platform/css/cf-enhancements/base.less
Firefox will only print the first page of content within an element with `display: inline-block`, which the capital-framework grid system uses for layout.
- Change the display of the `main_content` to block when printing the page.
- @rrstoll 
> Fix printing in Firefox for main content

- setup.py
- tox.ini
Stop testing against Django 1.8 as cfgov-refresh no longer supports it. Remove support for Django 1.8/9/10 from setup.py.
> Deprecate support for Django < 1.11

- teachers_digital_platform/css/utilities/hide-on.less
- teachers_digital_platform/jinja2/teachers_digital_platform/activity_search_facets_and_results.html
Allow search filters to be applied if JS is disabled.
- @nbucknor 
- @rrstoll 
> Allow search filters to be applied if JS is disabled

- teachers_digital_platform/models/pages.py
- teachers_digital_platform/search_indexes.py
- teachers_digital_platform/tests/models/test_activity_index_page.py
Allow admins to move ActivityPages to the Trash folder.
- @willbarton @chosak @Scotchester 
1. In Wagtail admin, navigate to the Activity Search page (/admin/pages/11875/)
2. Hover over an activity in the list and click "More"
3. From the dropdown, choose "Move"
4. The Search page and HomePage pages should be the only selectable options
5. Click "Trash"
6. Click "Yes, move this page" button
- Because Activity pages can be moved to the Trash folder, we'll need to rely on a periodic  or manual process for updating the search index after pages are moved to the trash.
> [TDP] Allow ActivityPages to go into the Trash and other HomePages

- README.md
Addressing the requests from @Scotchester 
> There are a couple areas where I'd like to see some clarification/elaboration:
> 
> 1. It would be nice to see a higher-level description of how the search interface integrates with Wagtail. In particular, how someone would set up the various bits of activity data and then the two types of pages necessary to actually see this thing in action.
> 2. Specific instructions for viewing the building blocks tool locally would be helpful, too.
> 3. Do the CSS and JS instructions apply to all 3 of the tools? It would be good to make this explicit.
> 4. Please remove the boilerplate from the top of the README, and consider adding a table of contents to the major sections, since this file ended up being pretty long.
> 
> Thanks!
1. high-level description …
> [TDP] Tweaking README to include TOC and more explicit descriptions

- setup.sh
The `setup.sh` script install step currently initiates two frontend builds: first, one under the `teachers_digital_platform/crtool` subdirectory (for the CRTool) and then a second one in the root
directory.
This first step is unnecessary, though, as the `package.json` "postinstall" script [already invokes the CRTool build](https://github.com/cfpb/teachers-digital-platform/blob/3e86033698ff827570e03e753861a03386343c89/package.json#L16).
To confirm, manually delete `node_modules` both in the root and under `teachers_digital_platform/crtool`, and then run `setup.sh`. You'll see that both builds complete successfully.
You can also confirm the [local functionality of the tool](http://localhost:8000/practitioner-resources/youth-financial-education/curriculum-review/tool/).
> Remove duplicate CRTool frontend build

- teachers_digital_platform/crtool/package-lock.json
- teachers_digital_platform/crtool/src/__tests__/DistinctiveButton.test.js
Clearing out `node_modules` and `package-lock.json` and reinstalling updated several subdependencies that should clear out some vulnerabilities that Snyk is reporting.
1. Pull branch
1. `cd teachers_digital_platform/crtool/`
1. `rm -rf node_modules/ && npm install`
1. `npm run build` succeeds
1. `npm test` succeeds
- Still trying to figure out how to update `react-scripts` without a huge amount of effort to update ALL the React/Babel stuff, but that's for a future PR.
> Update crtool subdeps to fix some vulnerabilities

- teachers_digital_platform/js/search.js
- teachers_digital_platform/js/tdp-analytics.js
- Convert keywords to lowercase before sending to Analytics
- Send "keyword:0" as label for "noSearchResults"
- @kelleyholden will likely have to test this once it is deployed.
- @dcmouyard
> [TDP] send keywords that have no results to analytics

- install_cfgov_refresh.sh
[cfgov-refresh#5083](https://github.com/cfpb/cfgov-refresh/pull/5083) aims to make the cf.gov satellite apps (including this one) non-optional, meaning that they are treated the same as any other Python dependency. This is a bit problematic for TDP, because TDP both depends on and is depended on by cfgov-refresh.
This change modifies the install_cfgov_refresh.sh script so that it filters out teachers_digital_platform when installing cfgov-refresh dependencies. This avoids us installing a built wheel of this project which would hide the local directories that we really want to test.
> Don't try to install TDP into itself

- package-lock.json
- teachers_digital_platform/crtool/package-lock.json
- teachers_digital_platform/templates/search/indexes/teachers_digital_platform/activitypage_text.txt
Added more ActivityPage fields for indexing by Haystack
- run `manage.py update_index teachers_digital_platform`
- search for "comparison shopping" on "practitioner-resources/youth-financial-education/teach/activities/" page
- Fields like "Big Idea" should now be searched and results should be found for the search
- @dcmouyard 
> [TDP] Update search to index all Activity page fields

- teachers_digital_platform/jinja2/teachers_digital_platform/activity_search_result.html
Update ActivityPage Search result template to replace "Bloom's Taxonomy level" with "Activity duration"
- Go here "practitioner-resources/youth-financial-education/teach/activities/"
- "Activity duration" should appear below "Age range" in search results
- @dcmouyard
> [TDP] replace blooms taxonomy level with activity duration on search results

- README.md
- teachers_digital_platform/jinja2/teachers_digital_platform/activity_page.html
- teachers_digital_platform/models/pages.py
- teachers_digital_platform/tests/models/test_activity_page.py
Added an "Explore related resources" section to the bottom ActivityPage detail pages. This section has links for similar Activities, FDIC financial lessons, and Federal Reserve financial education resources.
- ActivityPage.get_subtopic_ids(): returns a set of all subtopic ids associated with a given ActivityPage. Used to generate a link for related Activities in the detail page template file.
- ActivityPage.get_grade_level_ids(): returns a list of all grade level ids associated with a given ActivityPage. Used to generate a link for related Activities in the detail page template file.
- ActivityPage.get_related_activities_url(): returns a relative url string with search parameters that
match the subtopics and grade level of a given ActivityPage.
- @dcmouyard  @cfpb/cfgov-backends 
[Preview …
> [TDP] similar activities block

- teachers_digital_platform/jinja2/teachers_digital_platform/activity_page.html
@lfatty reported that these links were targeting `_blank` but didn't have `rel="noopener noreferrer"` added, which is potentially a security vulnerability. This PR adds those attributes.
- Adds `rel="noopener noreferrer"` to external links that targeted `_blank`
- The two affected links should function as before.
> Add rel="noopener noreferrer" to target blank links

- .travis.yml
- setup.py
- tox.ini
Remove references to python 2 from tox, travis, and setup.py.
> Remove python 2

- teachers_digital_platform/crtool/src/__tests__/__snapshots__/ContentElementaryCriterionPage.test.js.snap
- teachers_digital_platform/crtool/src/__tests__/__snapshots__/ContentHighCriterionPage.test.js.snap
- teachers_digital_platform/crtool/src/__tests__/__snapshots__/ContentMiddleCriterionPage.test.js.snap
- teachers_digital_platform/crtool/src/__tests__/__snapshots__/EfficacyCriterionPage.test.js.snap
- teachers_digital_platform/crtool/src/__tests__/__snapshots__/QualityCriterionPage.test.js.snap
- teachers_digital_platform/crtool/src/__tests__/__snapshots__/UtilityCriterionPage.test.js.snap
- teachers_digital_platform/crtool/src/js/business.logic/constants.js
- teachers_digital_platform/jinja2/teachers_digital_platform/crt-start.html
- Change the "Download the curriculum review" link on the [CRTool Before you begin page](https://www.consumerfinance.gov/practitioner-resources/youth-financial-education/curriculum-review/before-you-begin/) to: https://files.consumerfinance.gov/f/documents/cfpb_youth-financial-education-curriculum-review-tool.pdf
- Change the "Learn more about how the review was developed" link in dimension intros  to: https://files.consumerfinance.gov/f/documents/cfpb_youth-financial-education-curriculum-report.pdf
- Changed URL from "https://files.consumerfinance.gov/f/201509_cfpb_youth-financial-education-curriculum-review.pdf" to "https://files.consumerfinance.gov/f/documents/cfpb_youth-financial-education-curriculum-review-tool.pdf"
- Changed URL from …
> [CRTOOL] Update PDF links

- teachers_digital_platform/crtool/src/js/components/pages/efficacy/EfficacyCriterion.js
- teachers_digital_platform/crtool/src/js/components/pages/efficacy/EfficacyCriterionPage.js
- teachers_digital_platform/crtool/src/js/components/pages/efficacy/EfficacyCriterionRow.js
- teachers_digital_platform/crtool/src/js/components/pages/quality/QualityCriterion.js
- teachers_digital_platform/crtool/src/js/components/pages/quality/QualityCriterionComponent.js
- teachers_digital_platform/crtool/src/js/components/pages/utility/UtilityCriterion.js
- teachers_digital_platform/crtool/src/js/components/pages/utility/UtilityCriterionComponent.js
This fix would allow someone to remove their first study in Criterion 1, while safeguarding against them getting rid of all their studies. Currently, the first study does not have a "remove a study" link next to it ever, even as they start adding other studies.
- Allow for the removal of the first study item without allowing for the removal of all studies
- Fix complete statuses for efficacy, quality, and utility. Completion statuses for those three dimensions were prematurely marking criteria as complete after the first answer has been filled in. This makes it so the complete flag isn't displayed until all answers in a criteria are filled out.
- Navigate to /practitioner-resources/youth-financial-education/curriculum-review/tool/
- Start a Curriculum Review
- Open the "Efficacy" …
> [CRTOOL] Allow for the removal of the first study item.

- teachers_digital_platform/crtool/src/js/components/dialogs/RemoveEfficacyStudyModal.js
- teachers_digital_platform/crtool/src/js/components/pages/partial.pages/EfficacyStudyComponent.js
Currently, we allow users to remove a second "study" they're working on under Efficacy with one click. I would expect there to be an interstitial modal before allowing them to (potentially inadvertently) delete the work they've just done on that new study.
- There is a new confirmation modal that appears when you click the button to remove an efficacy study.
- There are new Analytics events for opening and closing the modal window. New events include:
- Modal opened:
- action: "link clicked: Remove efficacy study", label: "Remove"
- Modal closed: 
- action: "Remove efficacy study modal", label: "Close"
- action: "Remove efficacy study modal", label: "No, keep it" 
- Navigate to /practitioner-resources/youth-financial-education/curriculum-review/tool/
- Start a Curriculum Review
- Open the …
> [CRTOOL] Add a confirmation modal for the Remove Efficacy Study button

- setup.py
#371 added support for Wagtail 2.3 but also modified setup.py to make 2.3 the minimal supported Wagtail version. We still want to support Wagtail 1.13.
If you're working on cfgov-refresh against 1.13, you should be able to `pip install` TDP without getting upgraded to 2.3.
> Restore Wagtail 1.13 support to setup.py

- .github/workflows/release.yml
This change adds a GitHub Actions workflow that will trigger on a new release being published. The workflow will build this package's wheel and source distribution files and then upload them to GitHub attached to that new release.
You can see an example of this action in, erm, action here: https://github.com/willbarton/teachers-digital-platform/runs/605991641?check_suite_focus=true
> Add an action to attach the wheel to releases

- setup.py
- tox.ini
This PR bumps support for versions of Wagtail up to 2.5, and makes `unittest-future` test against Django 2.2 and Wagtail 2.5.
> Support Wagtail up to 2.5

- teachers_digital_platform/jinja2/teachers_digital_platform/activity_search_facets_and_results.html
When a user gets the "No results match your search." message is the footer message needed since no actitivites are listed
- Hide the div.results_footer block when no results are found for a search.
- @Scotchester
> [TDP] Only display div.results_footer when there are results.

- teachers_digital_platform/models/pages.py
An update to flake8 is catching more linting errors now. This fixes the new ones flake8 has found.
- tox -e lint
> Fix newly surfaced Python linting errors

- setup.py
- tox.ini
Removed `not_skip` and `recursive` from `tox.ini` to fix
TypeError: __init__() got an unexpected keyword argument 'not_skip'
Prior to version 5.0.0, isort wouldn't automatically traverse directories. The --recursive option was necessary to tell it to do so. In 5.0.0 directories are automatically traversed for all Python files, and as such this option is no longer necessary and should simply be removed.
In an earlier version isort had a default skip of __init__.py. To get around that many projects wanted a way to not skip __init__.py or any other files that were automatically skipped in the future by isort. isort no longer has any default skips, so if the value here is __init__.py you can simply remove the setting.
https://timothycrosley.github.io/isort/docs/upgrade_guides/5.0.0/
Short …
> Updates to support isort 5.0

- crtool/jinja2/crtool/crt-base.html
This file is not needed in the CR Tool, and it in fact does not exist anymore, which was causing a 500 when Django could not find it.
- Eliminates unnecessary inclusion of the (now-defunct) `tdp.js` file in `crt-base.html`
- In a future PR, we should clean up all other references in this PR to the string `tdp`, which is muddying the waters when this repo no longer has a code-based connection to the other TDP stuff.
> Remove reference to unnecessary tdp.js file

- setup.py
It doesn't look like this repository needs the [django-js-asset](https://pypi.org/project/django-js-asset/) dependency any longer, if it ever did.
While I'm in here I'm correcting the setup.py URL to the renamed one.
[Grep the code for any use of `js_asset`.](https://github.com/cfpb/curriculum-review-tool/search?q=js_asset&unscoped_q=js_asset)
> Remove unnecessary django-js-asset dependency

- package-lock.json
- package.json
- src/__tests__/app_test.js
- src/__tests__/crtoolLocalStorage/init_test.js
- src/crtoolLocalStorage.js
- src/jest/setup.js
Add tests for crtoolLocalStorage.init and also fixe a couple corner cases found via tests!
Enables async tests
---
- babel-polyfill
- unit tests for crtoolLocalStorage init()
> Add tests for crtoolLocalStorage.init

- .eslintrc
- .github/workflows/ci.yml
- .gitignore
- README.md
- crtool/css/crtool.less
- crtool/css/temp/button-links.less
- crtool/css/temp/cf-icons.less
- setup.py
- tox.ini
This change updates our supported version range to the LTS release of Django (2.2) and the current release of Django (3.1).
- Added support for Django 3.1
- Removed support for Django 1.11
> Support LTS + Current versions of Django

- crtool/jinja2/crtool/crt-start.html
- crtool/js/startPage.js
- crtool/tests/test_views.py
- crtool/urls.py
- crtool/views.py
- setup.py
- src/__tests__/crtoolLocalStorage/init_test.js
- src/crtoolLocalStorage.js
Merging in some of Steve Clay's optimizations:
- Move id storage to URL hash instead of query string
- Make all forms use POST instead of GET
> store curriculumId in a url hash instead of a querystring

- setup.py
We need to switch to the binary version of psycopg to resolve the following error:
```
[2020-09-28T20:58:23.289Z] #10 9.409 Collecting psycopg2>=2.8.4
[2020-09-28T20:58:23.289Z] #10 9.423   Downloading psycopg2-2.8.6.tar.gz (383 kB)
[2020-09-28T20:58:23.556Z] #10 9.845     ERROR: Command errored out with exit status 1:
[2020-09-28T20:58:23.556Z] #10 9.845      command: /opt/rh/rh-python36/root/usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-fcoovvjy/psycopg2/setup.py'"'"'; __file__='"'"'/tmp/pip-install-fcoovvjy/psycopg2/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-pkv76heq …
```
> Switch to the binary version of psycopg2-binary

- crtool/tests/settings.py
- crtool/views.py
We've removed CSRF from non-authenticated paths in cfpb/consumerfinance.gov#6366. The PR removes the CSRF middleware from the standalone testing settings and removes the `csrf_exempt` decorator from views, as it is no longer needed.
> Remove CSRF middleware and csrf_exempt

- crtool/jinja2/crtool/crt-start.html
- crtool/js/startPage.js
- crtool/tests/test_views.py
- crtool/views.py
Limits the acceptable size of review entry and formally catches JSONDecodeError instead of litting Django deal with it.
---
- Returns 400 status if request body limit too large
- Returns 400 status if request body is invalid JSON
- Adds unit tests for those
Run unit tests.
> Limit review size and catch bad JSON

- crtool/jinja2/crtool/crt-start.html
- crtool/tests/test_views.py
- crtool/views.py
Limits title input to 150 chars and pub date to 50, and validates input type as well.
- Validate title and pub_date string len directly instead of the combined JSON input size.
- Refactors views to use return-early for easier reading.
- Eliminates pass_code input handling as this is no longer used.
> Limit title to 150 chars

- crtool/jinja2/crtool/crt-start.html
This replicates the functionality of layout-2-1-bleedbar.html after cfpb/consumerfinance.gov/pull/7164 (and layout-2-1-bleedbar.html is being removed).
> Switch to layout-2-1.html base-template
